version: '3'
services:
  express-app:
    build: .
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/
    ports:
      - "8000:8000"
    command: bash -c "sleep 5 && npm start"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: